/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/

-- Find total customers by countries
select 
country, 
count(customer_key) as total_customers 
from gold.dim_customers 
group by country 
order by total_customers desc

-- Find total customers by gender
select 
gender, 
count(customer_key) as total_customers
from gold.dim_customers 
group by gender
order by total_customers desc

-- Find total products by category
select 
category, 
count(product_name) as total_products 
from gold.dim_products 
group by category
order by total_products desc

-- What is the average costs in each category
select 
category, 
avg(cost) as average_cost
from gold.dim_products 
group by category
order by average_cost desc

-- What is the total revenue generated for each category?
select 
p.category,
sum(f.sales_amount) as total_revenue
from gold.fact_sales f
left join gold.dim_products p
on p.product_key = f.product_key
group by p.category
order by total_revenue desc

-- Find total revenue generated by each customer
select
c.customer_key,
c.first_name,
c.last_name,
sum(f.sales_amount) as total_revenue
from gold.fact_sales f
left join gold.dim_customers c
on f.customer_key = c.customer_key
group by c.customer_key, c.first_name, c.last_name
order by total_revenue desc

-- What is the distribution of sold items across countries?
select
c.country,
sum(f.quantity) as total_sold_items
from gold.fact_sales f
left join gold.dim_customers c
on f.customer_key = c.customer_key
group by c.country
order by total_sold_items desc

